// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kudora/integrity/v1/integrity_set.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// IntegritySet defines the IntegritySet message.
type IntegritySet struct {
	Tenant      string `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Type        string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Period      string `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	Root        string `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	Creator     string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	BlockHeight uint64 `protobuf:"varint,6,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BlockTime   string `protobuf:"bytes,7,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	RecordCount uint64 `protobuf:"varint,8,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
}

func (m *IntegritySet) Reset()         { *m = IntegritySet{} }
func (m *IntegritySet) String() string { return proto.CompactTextString(m) }
func (*IntegritySet) ProtoMessage()    {}
func (*IntegritySet) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d16ea7dcb2350a, []int{0}
}
func (m *IntegritySet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IntegritySet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IntegritySet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IntegritySet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegritySet.Merge(m, src)
}
func (m *IntegritySet) XXX_Size() int {
	return m.Size()
}
func (m *IntegritySet) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegritySet.DiscardUnknown(m)
}

var xxx_messageInfo_IntegritySet proto.InternalMessageInfo

func (m *IntegritySet) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *IntegritySet) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *IntegritySet) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *IntegritySet) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *IntegritySet) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *IntegritySet) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *IntegritySet) GetBlockTime() string {
	if m != nil {
		return m.BlockTime
	}
	return ""
}

func (m *IntegritySet) GetRecordCount() uint64 {
	if m != nil {
		return m.RecordCount
	}
	return 0
}

// IntegritySetBundle defines one integrity set together with its sorted records.
type IntegritySetBundle struct {
	Set     IntegritySet      `protobuf:"bytes,1,opt,name=set,proto3" json:"set"`
	Records []IntegrityRecord `protobuf:"bytes,2,rep,name=records,proto3" json:"records"`
}

func (m *IntegritySetBundle) Reset()         { *m = IntegritySetBundle{} }
func (m *IntegritySetBundle) String() string { return proto.CompactTextString(m) }
func (*IntegritySetBundle) ProtoMessage()    {}
func (*IntegritySetBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d16ea7dcb2350a, []int{1}
}
func (m *IntegritySetBundle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IntegritySetBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IntegritySetBundle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IntegritySetBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegritySetBundle.Merge(m, src)
}
func (m *IntegritySetBundle) XXX_Size() int {
	return m.Size()
}
func (m *IntegritySetBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegritySetBundle.DiscardUnknown(m)
}

var xxx_messageInfo_IntegritySetBundle proto.InternalMessageInfo

func (m *IntegritySetBundle) GetSet() IntegritySet {
	if m != nil {
		return m.Set
	}
	return IntegritySet{}
}

func (m *IntegritySetBundle) GetRecords() []IntegrityRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*IntegritySet)(nil), "kudora.integrity.v1.IntegritySet")
	proto.RegisterType((*IntegritySetBundle)(nil), "kudora.integrity.v1.IntegritySetBundle")
}

func init() {
	proto.RegisterFile("kudora/integrity/v1/integrity_set.proto", fileDescriptor_48d16ea7dcb2350a)
}

var fileDescriptor_48d16ea7dcb2350a = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x86, 0xbd, 0xe0, 0x42, 0x59, 0x38, 0x6d, 0xab, 0x6a, 0x85, 0x54, 0x17, 0x50, 0xa5, 0xa2,
	0x1e, 0x6c, 0x41, 0x0f, 0x55, 0xaf, 0xb4, 0x87, 0xe6, 0x18, 0x27, 0xca, 0x21, 0x17, 0x64, 0xec,
	0x91, 0x59, 0x81, 0xbd, 0x68, 0x3d, 0x46, 0xe1, 0x2d, 0x72, 0xc9, 0x3b, 0x71, 0xe4, 0x98, 0x53,
	0x14, 0x81, 0xf2, 0x1e, 0xd1, 0xee, 0x42, 0x42, 0xa4, 0x88, 0xdb, 0xcc, 0x3f, 0xdf, 0x3f, 0xab,
	0xd9, 0x9f, 0xfe, 0x98, 0x95, 0x89, 0x54, 0x51, 0x20, 0x72, 0x84, 0x54, 0x09, 0x5c, 0x05, 0xcb,
	0xc1, 0x6b, 0x33, 0x2e, 0x00, 0xfd, 0x85, 0x92, 0x28, 0xd9, 0x27, 0x0b, 0xfa, 0x2f, 0x33, 0x7f,
	0x39, 0x68, 0x7f, 0x4e, 0x65, 0x2a, 0xcd, 0x3c, 0xd0, 0x95, 0x45, 0xdb, 0x3f, 0x4f, 0xef, 0x54,
	0x10, 0x4b, 0x95, 0x58, 0xb6, 0xf7, 0x44, 0x68, 0xeb, 0xec, 0x30, 0xba, 0x00, 0x64, 0x5f, 0x68,
	0x0d, 0x21, 0x8f, 0x72, 0xe4, 0xa4, 0x43, 0xfa, 0x8d, 0x70, 0xdf, 0x31, 0x46, 0x5d, 0x5c, 0x2d,
	0x80, 0x57, 0x8c, 0x6a, 0x6a, 0xcd, 0x2e, 0x40, 0x09, 0x99, 0xf0, 0xaa, 0x65, 0x6d, 0xa7, 0x59,
	0x25, 0x25, 0x72, 0xd7, 0xb2, 0xba, 0x66, 0x9c, 0xd6, 0x63, 0x05, 0x11, 0x4a, 0xc5, 0x3f, 0x18,
	0xf9, 0xd0, 0xb2, 0x2e, 0x6d, 0x4d, 0xe6, 0x32, 0x9e, 0x8d, 0xa7, 0x20, 0xd2, 0x29, 0xf2, 0x5a,
	0x87, 0xf4, 0xdd, 0xb0, 0x69, 0xb4, 0xff, 0x46, 0x62, 0x5f, 0x29, 0xb5, 0x08, 0x8a, 0x0c, 0x78,
	0xdd, 0xf8, 0x1b, 0x46, 0xb9, 0x14, 0x19, 0xe8, 0x0d, 0xf6, 0xa8, 0x71, 0x2c, 0xcb, 0x1c, 0xf9,
	0x47, 0xbb, 0xc1, 0x6a, 0x7f, 0xb5, 0xd4, 0xbb, 0x23, 0x94, 0x1d, 0xdf, 0x39, 0x2a, 0xf3, 0x64,
	0x0e, 0xec, 0x0f, 0xad, 0x16, 0x60, 0x4f, 0x6d, 0x0e, 0xbb, 0xfe, 0x3b, 0x7f, 0xec, 0xbf, 0x71,
	0xb9, 0xeb, 0x87, 0x6f, 0x4e, 0xa8, 0x3d, 0xec, 0x1f, 0xad, 0xdb, 0x07, 0x0a, 0x5e, 0xe9, 0x54,
	0xfb, 0xcd, 0xe1, 0xf7, 0xd3, 0xf6, 0xd0, 0xc0, 0xfb, 0x0d, 0x07, 0xeb, 0xe8, 0x7c, 0xbd, 0xf5,
	0xc8, 0x66, 0xeb, 0x91, 0xc7, 0xad, 0x47, 0x6e, 0x77, 0x9e, 0xb3, 0xd9, 0x79, 0xce, 0xfd, 0xce,
	0x73, 0xae, 0x7f, 0xa7, 0x02, 0xa7, 0xe5, 0xc4, 0x8f, 0x65, 0x16, 0x5c, 0x45, 0x73, 0xc8, 0x51,
	0xe4, 0x23, 0x05, 0x09, 0x64, 0x50, 0xa0, 0x82, 0x60, 0x1f, 0xf2, 0xcd, 0x51, 0xcc, 0x3a, 0x94,
	0x62, 0x52, 0x33, 0xc9, 0xfe, 0x7a, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x83, 0x67, 0x46, 0x89, 0x5b,
	0x02, 0x00, 0x00,
}

func (m *IntegritySet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IntegritySet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IntegritySet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RecordCount != 0 {
		i = encodeVarintIntegritySet(dAtA, i, uint64(m.RecordCount))
		i--
		dAtA[i] = 0x40
	}
	if len(m.BlockTime) > 0 {
		i -= len(m.BlockTime)
		copy(dAtA[i:], m.BlockTime)
		i = encodeVarintIntegritySet(dAtA, i, uint64(len(m.BlockTime)))
		i--
		dAtA[i] = 0x3a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintIntegritySet(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintIntegritySet(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintIntegritySet(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Period) > 0 {
		i -= len(m.Period)
		copy(dAtA[i:], m.Period)
		i = encodeVarintIntegritySet(dAtA, i, uint64(len(m.Period)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintIntegritySet(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintIntegritySet(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IntegritySetBundle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IntegritySetBundle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IntegritySetBundle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Records) > 0 {
		for iNdEx := len(m.Records) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Records[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintIntegritySet(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Set.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintIntegritySet(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintIntegritySet(dAtA []byte, offset int, v uint64) int {
	offset -= sovIntegritySet(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IntegritySet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovIntegritySet(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovIntegritySet(uint64(l))
	}
	l = len(m.Period)
	if l > 0 {
		n += 1 + l + sovIntegritySet(uint64(l))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovIntegritySet(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovIntegritySet(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovIntegritySet(uint64(m.BlockHeight))
	}
	l = len(m.BlockTime)
	if l > 0 {
		n += 1 + l + sovIntegritySet(uint64(l))
	}
	if m.RecordCount != 0 {
		n += 1 + sovIntegritySet(uint64(m.RecordCount))
	}
	return n
}

func (m *IntegritySetBundle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Set.Size()
	n += 1 + l + sovIntegritySet(uint64(l))
	if len(m.Records) > 0 {
		for _, e := range m.Records {
			l = e.Size()
			n += 1 + l + sovIntegritySet(uint64(l))
		}
	}
	return n
}

func sovIntegritySet(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIntegritySet(x uint64) (n int) {
	return sovIntegritySet(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IntegritySet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIntegritySet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IntegritySet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IntegritySet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntegritySet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntegritySet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntegritySet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntegritySet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntegritySet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntegritySet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Period = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntegritySet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntegritySet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntegritySet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntegritySet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntegritySet
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntegritySet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordCount", wireType)
			}
			m.RecordCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecordCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIntegritySet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIntegritySet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IntegritySetBundle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIntegritySet
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IntegritySetBundle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IntegritySetBundle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Set", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIntegritySet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIntegritySet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Set.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Records", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIntegritySet
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIntegritySet
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Records = append(m.Records, IntegrityRecord{})
			if err := m.Records[len(m.Records)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIntegritySet(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIntegritySet
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIntegritySet(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIntegritySet
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIntegritySet
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIntegritySet
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIntegritySet
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIntegritySet
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIntegritySet        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIntegritySet          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIntegritySet = fmt.Errorf("proto: unexpected end of group")
)
