// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kudora/integrity/v1/integrity_record.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// IntegrityRecord defines the IntegrityRecord message.
type IntegrityRecord struct {
	Tag        string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Nonce      string `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext string `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (m *IntegrityRecord) Reset()         { *m = IntegrityRecord{} }
func (m *IntegrityRecord) String() string { return proto.CompactTextString(m) }
func (*IntegrityRecord) ProtoMessage()    {}
func (*IntegrityRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_19b0e68132b65075, []int{0}
}
func (m *IntegrityRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IntegrityRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IntegrityRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IntegrityRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegrityRecord.Merge(m, src)
}
func (m *IntegrityRecord) XXX_Size() int {
	return m.Size()
}
func (m *IntegrityRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegrityRecord.DiscardUnknown(m)
}

var xxx_messageInfo_IntegrityRecord proto.InternalMessageInfo

func (m *IntegrityRecord) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *IntegrityRecord) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *IntegrityRecord) GetCiphertext() string {
	if m != nil {
		return m.Ciphertext
	}
	return ""
}

func init() {
	proto.RegisterType((*IntegrityRecord)(nil), "kudora.integrity.v1.IntegrityRecord")
}

func init() {
	proto.RegisterFile("kudora/integrity/v1/integrity_record.proto", fileDescriptor_19b0e68132b65075)
}

var fileDescriptor_19b0e68132b65075 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xca, 0x2e, 0x4d, 0xc9,
	0x2f, 0x4a, 0xd4, 0xcf, 0xcc, 0x2b, 0x49, 0x4d, 0x2f, 0xca, 0x2c, 0xa9, 0xd4, 0x2f, 0x33, 0x44,
	0x70, 0xe2, 0x8b, 0x52, 0x93, 0xf3, 0x8b, 0x52, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84,
	0x21, 0x6a, 0xf5, 0xe0, 0xd2, 0x7a, 0x65, 0x86, 0x4a, 0x91, 0x5c, 0xfc, 0x9e, 0x30, 0x7e, 0x10,
	0x58, 0xb5, 0x90, 0x00, 0x17, 0x73, 0x49, 0x62, 0xba, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x88, 0x29, 0x24, 0xc2, 0xc5, 0x9a, 0x97, 0x9f, 0x97, 0x9c, 0x2a, 0xc1, 0x04, 0x16, 0x83, 0x70,
	0x84, 0xe4, 0xb8, 0xb8, 0x92, 0x33, 0x0b, 0x32, 0x52, 0x8b, 0x4a, 0x52, 0x2b, 0x4a, 0x24, 0x98,
	0xc1, 0x52, 0x48, 0x22, 0x4e, 0x81, 0x27, 0x1e, 0xc9, 0x31, 0x5e, 0x78, 0x24, 0xc7, 0xf8, 0xe0,
	0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31, 0xdc, 0x78, 0x2c, 0xc7, 0x10,
	0x65, 0x9e, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x1f, 0x96, 0x98, 0x93,
	0x9a, 0x57, 0x92, 0x99, 0xe7, 0x54, 0x94, 0x9a, 0x92, 0x9a, 0x9b, 0x5a, 0x5c, 0x52, 0x94, 0xaa,
	0x0f, 0xf5, 0x54, 0x05, 0x92, 0xb7, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0x3e, 0x31,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x14, 0x52, 0x89, 0xf7, 0x00, 0x00, 0x00,
}

func (m *IntegrityRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IntegrityRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IntegrityRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Ciphertext) > 0 {
		i -= len(m.Ciphertext)
		copy(dAtA[i:], m.Ciphertext)
		i = encodeVarintIntegrityRecord(dAtA, i, uint64(len(m.Ciphertext)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Nonce) > 0 {
		i -= len(m.Nonce)
		copy(dAtA[i:], m.Nonce)
		i = encodeVarintIntegrityRecord(dAtA, i, uint64(len(m.Nonce)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tag) > 0 {
		i -= len(m.Tag)
		copy(dAtA[i:], m.Tag)
		i = encodeVarintIntegrityRecord(dAtA, i, uint64(len(m.Tag)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIntegrityRecord(dAtA []byte, offset int, v uint64) int {
	offset -= sovIntegrityRecord(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IntegrityRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tag)
	if l > 0 {
		n += 1 + l + sovIntegrityRecord(uint64(l))
	}
	l = len(m.Nonce)
	if l > 0 {
		n += 1 + l + sovIntegrityRecord(uint64(l))
	}
	l = len(m.Ciphertext)
	if l > 0 {
		n += 1 + l + sovIntegrityRecord(uint64(l))
	}
	return n
}

func sovIntegrityRecord(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIntegrityRecord(x uint64) (n int) {
	return sovIntegrityRecord(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IntegrityRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIntegrityRecord
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IntegrityRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IntegrityRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegrityRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntegrityRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntegrityRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegrityRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntegrityRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntegrityRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nonce = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ciphertext", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIntegrityRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIntegrityRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIntegrityRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ciphertext = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIntegrityRecord(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIntegrityRecord
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIntegrityRecord(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIntegrityRecord
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIntegrityRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIntegrityRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIntegrityRecord
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIntegrityRecord
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIntegrityRecord
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIntegrityRecord        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIntegrityRecord          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIntegrityRecord = fmt.Errorf("proto: unexpected end of group")
)
