// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kudora/integrity/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgRegisterTenant defines the MsgRegisterTenant message.
type MsgRegisterTenant struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Tenant  string `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
}

func (m *MsgRegisterTenant) Reset()         { *m = MsgRegisterTenant{} }
func (m *MsgRegisterTenant) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterTenant) ProtoMessage()    {}
func (*MsgRegisterTenant) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{2}
}
func (m *MsgRegisterTenant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterTenant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterTenant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterTenant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterTenant.Merge(m, src)
}
func (m *MsgRegisterTenant) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterTenant) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterTenant.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterTenant proto.InternalMessageInfo

func (m *MsgRegisterTenant) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterTenant) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

// MsgRegisterTenantResponse defines the MsgRegisterTenantResponse message.
type MsgRegisterTenantResponse struct {
}

func (m *MsgRegisterTenantResponse) Reset()         { *m = MsgRegisterTenantResponse{} }
func (m *MsgRegisterTenantResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterTenantResponse) ProtoMessage()    {}
func (*MsgRegisterTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{3}
}
func (m *MsgRegisterTenantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterTenantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterTenantResponse.Merge(m, src)
}
func (m *MsgRegisterTenantResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterTenantResponse proto.InternalMessageInfo

// MsgTransferTenantOwnership defines the MsgTransferTenantOwnership message.
type MsgTransferTenantOwnership struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Tenant   string `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	NewOwner string `protobuf:"bytes,3,opt,name=new_owner,json=newOwner,proto3" json:"new_owner,omitempty"`
}

func (m *MsgTransferTenantOwnership) Reset()         { *m = MsgTransferTenantOwnership{} }
func (m *MsgTransferTenantOwnership) String() string { return proto.CompactTextString(m) }
func (*MsgTransferTenantOwnership) ProtoMessage()    {}
func (*MsgTransferTenantOwnership) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{4}
}
func (m *MsgTransferTenantOwnership) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferTenantOwnership) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferTenantOwnership.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferTenantOwnership) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferTenantOwnership.Merge(m, src)
}
func (m *MsgTransferTenantOwnership) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferTenantOwnership) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferTenantOwnership.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferTenantOwnership proto.InternalMessageInfo

func (m *MsgTransferTenantOwnership) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgTransferTenantOwnership) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *MsgTransferTenantOwnership) GetNewOwner() string {
	if m != nil {
		return m.NewOwner
	}
	return ""
}

// MsgTransferTenantOwnershipResponse defines the MsgTransferTenantOwnershipResponse message.
type MsgTransferTenantOwnershipResponse struct {
}

func (m *MsgTransferTenantOwnershipResponse) Reset()         { *m = MsgTransferTenantOwnershipResponse{} }
func (m *MsgTransferTenantOwnershipResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransferTenantOwnershipResponse) ProtoMessage()    {}
func (*MsgTransferTenantOwnershipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{5}
}
func (m *MsgTransferTenantOwnershipResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferTenantOwnershipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferTenantOwnershipResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferTenantOwnershipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferTenantOwnershipResponse.Merge(m, src)
}
func (m *MsgTransferTenantOwnershipResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferTenantOwnershipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferTenantOwnershipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferTenantOwnershipResponse proto.InternalMessageInfo

// MsgAcceptTenantOwnership defines the MsgAcceptTenantOwnership message.
type MsgAcceptTenantOwnership struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Tenant  string `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
}

func (m *MsgAcceptTenantOwnership) Reset()         { *m = MsgAcceptTenantOwnership{} }
func (m *MsgAcceptTenantOwnership) String() string { return proto.CompactTextString(m) }
func (*MsgAcceptTenantOwnership) ProtoMessage()    {}
func (*MsgAcceptTenantOwnership) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{6}
}
func (m *MsgAcceptTenantOwnership) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAcceptTenantOwnership) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAcceptTenantOwnership.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAcceptTenantOwnership) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAcceptTenantOwnership.Merge(m, src)
}
func (m *MsgAcceptTenantOwnership) XXX_Size() int {
	return m.Size()
}
func (m *MsgAcceptTenantOwnership) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAcceptTenantOwnership.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAcceptTenantOwnership proto.InternalMessageInfo

func (m *MsgAcceptTenantOwnership) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAcceptTenantOwnership) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

// MsgAcceptTenantOwnershipResponse defines the MsgAcceptTenantOwnershipResponse message.
type MsgAcceptTenantOwnershipResponse struct {
}

func (m *MsgAcceptTenantOwnershipResponse) Reset()         { *m = MsgAcceptTenantOwnershipResponse{} }
func (m *MsgAcceptTenantOwnershipResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAcceptTenantOwnershipResponse) ProtoMessage()    {}
func (*MsgAcceptTenantOwnershipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{7}
}
func (m *MsgAcceptTenantOwnershipResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAcceptTenantOwnershipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAcceptTenantOwnershipResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAcceptTenantOwnershipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAcceptTenantOwnershipResponse.Merge(m, src)
}
func (m *MsgAcceptTenantOwnershipResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAcceptTenantOwnershipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAcceptTenantOwnershipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAcceptTenantOwnershipResponse proto.InternalMessageInfo

// MsgCancelTenantOwnershipTransfer defines the MsgCancelTenantOwnershipTransfer message.
type MsgCancelTenantOwnershipTransfer struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Tenant  string `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
}

func (m *MsgCancelTenantOwnershipTransfer) Reset()         { *m = MsgCancelTenantOwnershipTransfer{} }
func (m *MsgCancelTenantOwnershipTransfer) String() string { return proto.CompactTextString(m) }
func (*MsgCancelTenantOwnershipTransfer) ProtoMessage()    {}
func (*MsgCancelTenantOwnershipTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{8}
}
func (m *MsgCancelTenantOwnershipTransfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelTenantOwnershipTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelTenantOwnershipTransfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelTenantOwnershipTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelTenantOwnershipTransfer.Merge(m, src)
}
func (m *MsgCancelTenantOwnershipTransfer) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelTenantOwnershipTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelTenantOwnershipTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelTenantOwnershipTransfer proto.InternalMessageInfo

func (m *MsgCancelTenantOwnershipTransfer) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCancelTenantOwnershipTransfer) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

// MsgCancelTenantOwnershipTransferResponse defines the MsgCancelTenantOwnershipTransferResponse message.
type MsgCancelTenantOwnershipTransferResponse struct {
}

func (m *MsgCancelTenantOwnershipTransferResponse) Reset() {
	*m = MsgCancelTenantOwnershipTransferResponse{}
}
func (m *MsgCancelTenantOwnershipTransferResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelTenantOwnershipTransferResponse) ProtoMessage()    {}
func (*MsgCancelTenantOwnershipTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{9}
}
func (m *MsgCancelTenantOwnershipTransferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelTenantOwnershipTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelTenantOwnershipTransferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelTenantOwnershipTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelTenantOwnershipTransferResponse.Merge(m, src)
}
func (m *MsgCancelTenantOwnershipTransferResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelTenantOwnershipTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelTenantOwnershipTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelTenantOwnershipTransferResponse proto.InternalMessageInfo

// MsgCommitIntegritySet defines the MsgCommitIntegritySet message.
type MsgCommitIntegritySet struct {
	Creator string            `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Tenant  string            `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Type    string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Period  string            `protobuf:"bytes,4,opt,name=period,proto3" json:"period,omitempty"`
	Root    string            `protobuf:"bytes,5,opt,name=root,proto3" json:"root,omitempty"`
	Records []IntegrityRecord `protobuf:"bytes,6,rep,name=records,proto3" json:"records"`
}

func (m *MsgCommitIntegritySet) Reset()         { *m = MsgCommitIntegritySet{} }
func (m *MsgCommitIntegritySet) String() string { return proto.CompactTextString(m) }
func (*MsgCommitIntegritySet) ProtoMessage()    {}
func (*MsgCommitIntegritySet) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{10}
}
func (m *MsgCommitIntegritySet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCommitIntegritySet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCommitIntegritySet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCommitIntegritySet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCommitIntegritySet.Merge(m, src)
}
func (m *MsgCommitIntegritySet) XXX_Size() int {
	return m.Size()
}
func (m *MsgCommitIntegritySet) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCommitIntegritySet.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCommitIntegritySet proto.InternalMessageInfo

func (m *MsgCommitIntegritySet) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCommitIntegritySet) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *MsgCommitIntegritySet) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MsgCommitIntegritySet) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *MsgCommitIntegritySet) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *MsgCommitIntegritySet) GetRecords() []IntegrityRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

// MsgCommitIntegritySetResponse defines the MsgCommitIntegritySetResponse message.
type MsgCommitIntegritySetResponse struct {
}

func (m *MsgCommitIntegritySetResponse) Reset()         { *m = MsgCommitIntegritySetResponse{} }
func (m *MsgCommitIntegritySetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCommitIntegritySetResponse) ProtoMessage()    {}
func (*MsgCommitIntegritySetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_52ea9faa3d85ec16, []int{11}
}
func (m *MsgCommitIntegritySetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCommitIntegritySetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCommitIntegritySetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCommitIntegritySetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCommitIntegritySetResponse.Merge(m, src)
}
func (m *MsgCommitIntegritySetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCommitIntegritySetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCommitIntegritySetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCommitIntegritySetResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "kudora.integrity.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "kudora.integrity.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgRegisterTenant)(nil), "kudora.integrity.v1.MsgRegisterTenant")
	proto.RegisterType((*MsgRegisterTenantResponse)(nil), "kudora.integrity.v1.MsgRegisterTenantResponse")
	proto.RegisterType((*MsgTransferTenantOwnership)(nil), "kudora.integrity.v1.MsgTransferTenantOwnership")
	proto.RegisterType((*MsgTransferTenantOwnershipResponse)(nil), "kudora.integrity.v1.MsgTransferTenantOwnershipResponse")
	proto.RegisterType((*MsgAcceptTenantOwnership)(nil), "kudora.integrity.v1.MsgAcceptTenantOwnership")
	proto.RegisterType((*MsgAcceptTenantOwnershipResponse)(nil), "kudora.integrity.v1.MsgAcceptTenantOwnershipResponse")
	proto.RegisterType((*MsgCancelTenantOwnershipTransfer)(nil), "kudora.integrity.v1.MsgCancelTenantOwnershipTransfer")
	proto.RegisterType((*MsgCancelTenantOwnershipTransferResponse)(nil), "kudora.integrity.v1.MsgCancelTenantOwnershipTransferResponse")
	proto.RegisterType((*MsgCommitIntegritySet)(nil), "kudora.integrity.v1.MsgCommitIntegritySet")
	proto.RegisterType((*MsgCommitIntegritySetResponse)(nil), "kudora.integrity.v1.MsgCommitIntegritySetResponse")
}

func init() { proto.RegisterFile("kudora/integrity/v1/tx.proto", fileDescriptor_52ea9faa3d85ec16) }

var fileDescriptor_52ea9faa3d85ec16 = []byte{
	// 706 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0x4d, 0x4f, 0xd5, 0x4c,
	0x14, 0xc7, 0x6f, 0x1f, 0xe0, 0xf2, 0xdc, 0x03, 0xd1, 0x50, 0x41, 0x4a, 0x91, 0xcb, 0x4d, 0x43,
	0xcc, 0x4d, 0x23, 0x6d, 0xb8, 0x06, 0x49, 0x48, 0x34, 0xe1, 0xea, 0xc6, 0xc5, 0x8d, 0x5a, 0xd0,
	0x85, 0x1b, 0x52, 0xda, 0x71, 0x6e, 0x23, 0x9d, 0x69, 0x66, 0x86, 0xb7, 0x44, 0x13, 0xa3, 0x3b,
	0x57, 0x6e, 0xfc, 0x0e, 0x6e, 0x4c, 0x58, 0xf8, 0x01, 0x5c, 0xb2, 0x24, 0xae, 0x5c, 0x19, 0x03,
	0x0b, 0x56, 0xae, 0xdd, 0x9a, 0xbe, 0x22, 0xa5, 0xe5, 0xc5, 0xc0, 0xa6, 0xe9, 0xcc, 0xf9, 0x9d,
	0x73, 0xfe, 0x67, 0x32, 0xe7, 0x0c, 0xdc, 0x78, 0xb9, 0xe6, 0x52, 0x66, 0x9b, 0x1e, 0x11, 0x08,
	0x33, 0x4f, 0x6c, 0x99, 0xeb, 0x33, 0xa6, 0xd8, 0x34, 0x02, 0x46, 0x05, 0x95, 0xaf, 0xc5, 0x56,
	0x23, 0xb3, 0x1a, 0xeb, 0x33, 0xea, 0x90, 0xed, 0x7b, 0x84, 0x9a, 0xd1, 0x37, 0xe6, 0xd4, 0x51,
	0x87, 0x72, 0x9f, 0x72, 0xd3, 0xe7, 0x38, 0xf4, 0xf7, 0x39, 0x4e, 0x0c, 0x63, 0xb1, 0x61, 0x39,
	0x5a, 0x99, 0xf1, 0x22, 0x31, 0x0d, 0x63, 0x8a, 0x69, 0xbc, 0x1f, 0xfe, 0x25, 0xbb, 0x7a, 0x91,
	0x9e, 0x6c, 0xb1, 0xcc, 0x90, 0x43, 0x99, 0x9b, 0xb0, 0x8d, 0x22, 0x36, 0xb0, 0x99, 0xed, 0x27,
	0x39, 0xb4, 0xaf, 0x12, 0x5c, 0xed, 0x70, 0xfc, 0x34, 0x70, 0x6d, 0x81, 0x1e, 0x47, 0x16, 0xf9,
	0x0e, 0xd4, 0xec, 0x35, 0xd1, 0xa5, 0xa1, 0x83, 0x22, 0x35, 0xa4, 0x66, 0xad, 0xad, 0x7c, 0xfb,
	0x32, 0x3d, 0x9c, 0x88, 0x5b, 0x70, 0x5d, 0x86, 0x38, 0x5f, 0x14, 0xcc, 0x23, 0xd8, 0x3a, 0x44,
	0xe5, 0x7b, 0x50, 0x8d, 0x63, 0x2b, 0xff, 0x35, 0xa4, 0xe6, 0x40, 0x6b, 0xdc, 0x28, 0x38, 0x1c,
	0x23, 0x4e, 0xd2, 0xae, 0xed, 0xfc, 0x98, 0xac, 0x7c, 0x3a, 0xd8, 0xd6, 0x25, 0x2b, 0xf1, 0x9a,
	0x9f, 0x7d, 0x7b, 0xb0, 0xad, 0x1f, 0xc6, 0x7b, 0x7f, 0xb0, 0xad, 0x6b, 0x49, 0x01, 0x9b, 0x7f,
	0x95, 0x90, 0x93, 0xab, 0x8d, 0xc1, 0x68, 0x6e, 0xcb, 0x42, 0x3c, 0xa0, 0x84, 0x23, 0xcd, 0x87,
	0xa1, 0x0e, 0xc7, 0x16, 0xc2, 0x1e, 0x17, 0x88, 0x2d, 0x21, 0x62, 0x13, 0x21, 0xb7, 0xa0, 0xdf,
	0x61, 0xc8, 0x16, 0x94, 0x9d, 0x5a, 0x5c, 0x0a, 0xca, 0xd7, 0xa1, 0x2a, 0x22, 0xef, 0xa8, 0xb4,
	0x9a, 0x95, 0xac, 0xe6, 0x07, 0x43, 0xc9, 0x29, 0xa5, 0x8d, 0xc3, 0xd8, 0xb1, 0x74, 0x99, 0x96,
	0xcf, 0x12, 0xa8, 0x1d, 0x8e, 0x97, 0x98, 0x4d, 0xf8, 0x8b, 0xd4, 0xfa, 0x68, 0x83, 0x20, 0xc6,
	0xbb, 0x5e, 0x70, 0x91, 0xaa, 0xe4, 0x59, 0xa8, 0x11, 0xb4, 0xb1, 0x4c, 0xc3, 0xe0, 0x4a, 0xcf,
	0x29, 0xd1, 0xfe, 0x27, 0x68, 0x23, 0x92, 0x91, 0x2b, 0x66, 0x0a, 0xb4, 0x72, 0xb9, 0x59, 0x55,
	0x02, 0x94, 0x0e, 0xc7, 0x0b, 0x8e, 0x83, 0x02, 0x71, 0x89, 0x25, 0xe5, 0xb4, 0x69, 0xd0, 0x28,
	0xcb, 0x9a, 0x29, 0x7b, 0x15, 0x31, 0xf7, 0x6d, 0xe2, 0xa0, 0xd5, 0x1c, 0x93, 0x16, 0x75, 0x89,
	0x0a, 0x75, 0x68, 0x9e, 0x96, 0x3d, 0x53, 0xfa, 0x5b, 0x82, 0x91, 0x10, 0xa6, 0xbe, 0xef, 0x89,
	0x87, 0xe9, 0x3d, 0x5f, 0x44, 0x17, 0x7a, 0x55, 0x65, 0x19, 0x7a, 0xc5, 0x56, 0x80, 0xe2, 0xfb,
	0x60, 0x45, 0xff, 0x21, 0x1b, 0x20, 0xe6, 0x51, 0x57, 0xe9, 0x8d, 0xd9, 0x78, 0x15, 0xb2, 0x8c,
	0x52, 0xa1, 0xf4, 0xc5, 0x6c, 0xf8, 0x2f, 0x3f, 0x80, 0xfe, 0x78, 0xb6, 0x70, 0xa5, 0xda, 0xe8,
	0x69, 0x0e, 0xb4, 0xa6, 0x0a, 0xdb, 0x3b, 0xd3, 0x6f, 0x45, 0x70, 0xbb, 0x37, 0xec, 0x73, 0x2b,
	0x75, 0xcd, 0x9d, 0xd2, 0x24, 0x4c, 0x14, 0x16, 0x9e, 0x1e, 0x4d, 0xeb, 0x57, 0x1f, 0xf4, 0x74,
	0x38, 0x96, 0x57, 0x60, 0xf0, 0xc8, 0x88, 0x2a, 0xce, 0x9d, 0x1b, 0x03, 0xea, 0xad, 0xb3, 0x50,
	0x69, 0x2e, 0xb9, 0x0b, 0x57, 0x72, 0x93, 0xe2, 0x66, 0x99, 0xff, 0x51, 0x4e, 0x35, 0xce, 0xc6,
	0x65, 0x99, 0xde, 0x49, 0x30, 0x5a, 0x36, 0x07, 0xcc, 0xb2, 0x58, 0x25, 0x0e, 0xea, 0xdc, 0x39,
	0x1d, 0x32, 0x15, 0xaf, 0x61, 0xa4, 0xb8, 0x6f, 0xa7, 0xcb, 0x22, 0x16, 0xe2, 0xea, 0xec, 0xb9,
	0xf0, 0x2c, 0xfd, 0x47, 0x09, 0x26, 0x4e, 0xee, 0xce, 0xd2, 0xc0, 0x27, 0xba, 0xa9, 0x77, 0xff,
	0xc9, 0x2d, 0xd3, 0x25, 0x40, 0x2e, 0xe8, 0x44, 0xbd, 0x34, 0xe8, 0x31, 0x56, 0x6d, 0x9d, 0x9d,
	0x4d, 0xb3, 0xaa, 0x7d, 0x6f, 0xc2, 0xa7, 0xb0, 0xfd, 0x64, 0x67, 0xaf, 0x2e, 0xed, 0xee, 0xd5,
	0xa5, 0x9f, 0x7b, 0x75, 0xe9, 0xc3, 0x7e, 0xbd, 0xb2, 0xbb, 0x5f, 0xaf, 0x7c, 0xdf, 0xaf, 0x57,
	0x9e, 0xcf, 0x61, 0x4f, 0x74, 0xd7, 0x56, 0x0c, 0x87, 0xfa, 0xe6, 0x33, 0x7b, 0x15, 0x11, 0xe1,
	0x91, 0x36, 0x43, 0x2e, 0xf2, 0x11, 0x17, 0x0c, 0x99, 0x05, 0x0f, 0x65, 0xd8, 0xe2, 0x7c, 0xa5,
	0x1a, 0x3d, 0xf4, 0xb7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xc6, 0xf7, 0x95, 0xc8, 0x08,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// RegisterTenant defines the RegisterTenant RPC.
	RegisterTenant(ctx context.Context, in *MsgRegisterTenant, opts ...grpc.CallOption) (*MsgRegisterTenantResponse, error)
	// TransferTenantOwnership defines the TransferTenantOwnership RPC.
	TransferTenantOwnership(ctx context.Context, in *MsgTransferTenantOwnership, opts ...grpc.CallOption) (*MsgTransferTenantOwnershipResponse, error)
	// AcceptTenantOwnership defines the AcceptTenantOwnership RPC.
	AcceptTenantOwnership(ctx context.Context, in *MsgAcceptTenantOwnership, opts ...grpc.CallOption) (*MsgAcceptTenantOwnershipResponse, error)
	// CancelTenantOwnershipTransfer defines the CancelTenantOwnershipTransfer RPC.
	CancelTenantOwnershipTransfer(ctx context.Context, in *MsgCancelTenantOwnershipTransfer, opts ...grpc.CallOption) (*MsgCancelTenantOwnershipTransferResponse, error)
	// CommitIntegritySet defines the CommitIntegritySet RPC.
	CommitIntegritySet(ctx context.Context, in *MsgCommitIntegritySet, opts ...grpc.CallOption) (*MsgCommitIntegritySetResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/kudora.integrity.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterTenant(ctx context.Context, in *MsgRegisterTenant, opts ...grpc.CallOption) (*MsgRegisterTenantResponse, error) {
	out := new(MsgRegisterTenantResponse)
	err := c.cc.Invoke(ctx, "/kudora.integrity.v1.Msg/RegisterTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferTenantOwnership(ctx context.Context, in *MsgTransferTenantOwnership, opts ...grpc.CallOption) (*MsgTransferTenantOwnershipResponse, error) {
	out := new(MsgTransferTenantOwnershipResponse)
	err := c.cc.Invoke(ctx, "/kudora.integrity.v1.Msg/TransferTenantOwnership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AcceptTenantOwnership(ctx context.Context, in *MsgAcceptTenantOwnership, opts ...grpc.CallOption) (*MsgAcceptTenantOwnershipResponse, error) {
	out := new(MsgAcceptTenantOwnershipResponse)
	err := c.cc.Invoke(ctx, "/kudora.integrity.v1.Msg/AcceptTenantOwnership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelTenantOwnershipTransfer(ctx context.Context, in *MsgCancelTenantOwnershipTransfer, opts ...grpc.CallOption) (*MsgCancelTenantOwnershipTransferResponse, error) {
	out := new(MsgCancelTenantOwnershipTransferResponse)
	err := c.cc.Invoke(ctx, "/kudora.integrity.v1.Msg/CancelTenantOwnershipTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CommitIntegritySet(ctx context.Context, in *MsgCommitIntegritySet, opts ...grpc.CallOption) (*MsgCommitIntegritySetResponse, error) {
	out := new(MsgCommitIntegritySetResponse)
	err := c.cc.Invoke(ctx, "/kudora.integrity.v1.Msg/CommitIntegritySet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// RegisterTenant defines the RegisterTenant RPC.
	RegisterTenant(context.Context, *MsgRegisterTenant) (*MsgRegisterTenantResponse, error)
	// TransferTenantOwnership defines the TransferTenantOwnership RPC.
	TransferTenantOwnership(context.Context, *MsgTransferTenantOwnership) (*MsgTransferTenantOwnershipResponse, error)
	// AcceptTenantOwnership defines the AcceptTenantOwnership RPC.
	AcceptTenantOwnership(context.Context, *MsgAcceptTenantOwnership) (*MsgAcceptTenantOwnershipResponse, error)
	// CancelTenantOwnershipTransfer defines the CancelTenantOwnershipTransfer RPC.
	CancelTenantOwnershipTransfer(context.Context, *MsgCancelTenantOwnershipTransfer) (*MsgCancelTenantOwnershipTransferResponse, error)
	// CommitIntegritySet defines the CommitIntegritySet RPC.
	CommitIntegritySet(context.Context, *MsgCommitIntegritySet) (*MsgCommitIntegritySetResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) RegisterTenant(ctx context.Context, req *MsgRegisterTenant) (*MsgRegisterTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTenant not implemented")
}
func (*UnimplementedMsgServer) TransferTenantOwnership(ctx context.Context, req *MsgTransferTenantOwnership) (*MsgTransferTenantOwnershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferTenantOwnership not implemented")
}
func (*UnimplementedMsgServer) AcceptTenantOwnership(ctx context.Context, req *MsgAcceptTenantOwnership) (*MsgAcceptTenantOwnershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptTenantOwnership not implemented")
}
func (*UnimplementedMsgServer) CancelTenantOwnershipTransfer(ctx context.Context, req *MsgCancelTenantOwnershipTransfer) (*MsgCancelTenantOwnershipTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTenantOwnershipTransfer not implemented")
}
func (*UnimplementedMsgServer) CommitIntegritySet(ctx context.Context, req *MsgCommitIntegritySet) (*MsgCommitIntegritySetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitIntegritySet not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudora.integrity.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterTenant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudora.integrity.v1.Msg/RegisterTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterTenant(ctx, req.(*MsgRegisterTenant))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferTenantOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferTenantOwnership)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferTenantOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudora.integrity.v1.Msg/TransferTenantOwnership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferTenantOwnership(ctx, req.(*MsgTransferTenantOwnership))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AcceptTenantOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAcceptTenantOwnership)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AcceptTenantOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudora.integrity.v1.Msg/AcceptTenantOwnership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AcceptTenantOwnership(ctx, req.(*MsgAcceptTenantOwnership))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelTenantOwnershipTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelTenantOwnershipTransfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelTenantOwnershipTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudora.integrity.v1.Msg/CancelTenantOwnershipTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelTenantOwnershipTransfer(ctx, req.(*MsgCancelTenantOwnershipTransfer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CommitIntegritySet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCommitIntegritySet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CommitIntegritySet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudora.integrity.v1.Msg/CommitIntegritySet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CommitIntegritySet(ctx, req.(*MsgCommitIntegritySet))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kudora.integrity.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "RegisterTenant",
			Handler:    _Msg_RegisterTenant_Handler,
		},
		{
			MethodName: "TransferTenantOwnership",
			Handler:    _Msg_TransferTenantOwnership_Handler,
		},
		{
			MethodName: "AcceptTenantOwnership",
			Handler:    _Msg_AcceptTenantOwnership_Handler,
		},
		{
			MethodName: "CancelTenantOwnershipTransfer",
			Handler:    _Msg_CancelTenantOwnershipTransfer_Handler,
		},
		{
			MethodName: "CommitIntegritySet",
			Handler:    _Msg_CommitIntegritySet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kudora/integrity/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegisterTenant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterTenant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterTenant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterTenantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterTenantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterTenantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTransferTenantOwnership) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferTenantOwnership) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferTenantOwnership) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewOwner) > 0 {
		i -= len(m.NewOwner)
		copy(dAtA[i:], m.NewOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.NewOwner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferTenantOwnershipResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferTenantOwnershipResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferTenantOwnershipResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAcceptTenantOwnership) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAcceptTenantOwnership) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAcceptTenantOwnership) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAcceptTenantOwnershipResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAcceptTenantOwnershipResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAcceptTenantOwnershipResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelTenantOwnershipTransfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelTenantOwnershipTransfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelTenantOwnershipTransfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelTenantOwnershipTransferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelTenantOwnershipTransferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelTenantOwnershipTransferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCommitIntegritySet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCommitIntegritySet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCommitIntegritySet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Records) > 0 {
		for iNdEx := len(m.Records) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Records[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Period) > 0 {
		i -= len(m.Period)
		copy(dAtA[i:], m.Period)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Period)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Tenant) > 0 {
		i -= len(m.Tenant)
		copy(dAtA[i:], m.Tenant)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Tenant)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCommitIntegritySetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCommitIntegritySetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCommitIntegritySetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegisterTenant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterTenantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTransferTenantOwnership) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.NewOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgTransferTenantOwnershipResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAcceptTenantOwnership) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAcceptTenantOwnershipResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelTenantOwnershipTransfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCancelTenantOwnershipTransferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCommitIntegritySet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Tenant)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Period)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Records) > 0 {
		for _, e := range m.Records {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgCommitIntegritySetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterTenant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterTenant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterTenant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterTenantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterTenantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterTenantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferTenantOwnership) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferTenantOwnership: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferTenantOwnership: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferTenantOwnershipResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferTenantOwnershipResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferTenantOwnershipResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAcceptTenantOwnership) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAcceptTenantOwnership: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAcceptTenantOwnership: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAcceptTenantOwnershipResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAcceptTenantOwnershipResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAcceptTenantOwnershipResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelTenantOwnershipTransfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelTenantOwnershipTransfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelTenantOwnershipTransfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelTenantOwnershipTransferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelTenantOwnershipTransferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelTenantOwnershipTransferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCommitIntegritySet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCommitIntegritySet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCommitIntegritySet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tenant", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tenant = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Period", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Period = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Records", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Records = append(m.Records, IntegrityRecord{})
			if err := m.Records[len(m.Records)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCommitIntegritySetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCommitIntegritySetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCommitIntegritySetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
